### ISSUE TITLE
Select workspace to which data is imported

### ISSUE THREAD

**Issue by stadibo** [rage/concepts#162]
When in the data import view the user would have a dropdown next to the *open*-button where they could choose a workspace to which the data should be imported. The feature should then delete the *workspace*-field in the data and replace the value in the *workspaceId*-field (if there isn't one it will be created) with the selected workspace's id.

When it comes to importing a new workspace, then similar functionality could be provided for the name of the new workspace. Maybe a field where one can type in a name. The *workspaceId*-field would be removed if no workspace has been selected, etc...

**Comment by d471061c** [comment]
fixed in #179
