### ISSUE TITLE
Rework user guide

### ISSUE THREAD

**Issue by stadibo** [rage/concepts#309]

**Comment by tulir** [comment]
* New guide won't depend on workspace state. While it might be nice, it's too fragile in practice.
* Button (maybe a question mark) next to the bottom-right menu in the workspace navigation bar to open the guide.
* After opening guide, the info box has buttons for next/previous box and maybe also a show video button for the videos in #134.
* Optionally, the guide could have some kind of a sidebar to jump between different info boxes.
* For #134, we could also have a separate view that lists all the available videos.
