### ISSUE TITLE
High-level goals for workspace

### ISSUE THREAD

**Issue by stadibo** [rage/concepts#340]
i.e. What are the courses and concepts in the workspace working towards?

These should then be linked to concepts, which might help prevent "islands" of concepts that are linked to something in reality but not in the concept graph.

- Tavoitteet jotka kehittyvät kurssilta toiselle
    - E.g. todistaminen, tieteellisen tekstin lukeminen/tuottaminen, etc.
    - Tag based?
    - Linked to workspace?

Backend
- [x] "GOAL" level for concept
- [x] List for goal concepts in workspace table
- [x] New link type "course -> concept (goal)"

Frontend
- [x] New view
- [x] Similar to course mapper (incl. drawing links), but instead of courses and concepts, there are two panels: left side with courses, right side with goals.
- [x] Goals have a type (tag) e.g. "skill", "knowledge"
- [x] Type shown a subtitle in list element

**Comment by d471061c** [comment]
fixed in #509
