### ISSUE TITLE
Can hide course list to make space for opened course

### ISSUE THREAD

**Issue by juhapekkamoilanen** [rage/concepts#51]
Course list on the left:

![image](https://user-images.githubusercontent.com/16867703/58816285-df563880-8631-11e9-8cfa-2eae2174f73d.png)

The middle part of the page should have maximal space to fit many courses to the view. 

Maybe add a toggle to navbar or some other way to hide the course list?

**Comment by d471061c** [comment]
Should removing a course remove all prerequisites related to that course or just hide it?

**Comment by juhapekkamoilanen** [comment]
Just hide (from the middle view) I think
