### ISSUE TITLE
Flip matrix axes?

### ISSUE THREAD

**Issue by juhapekkamoilanen** [rage/concepts#55]
Course matrices have two axes: own-topics and prequisite-topics.

Current view:

![image](https://user-images.githubusercontent.com/16867703/58894284-5e16a880-86fa-11e9-9637-b56805cc0478.png)

Maybe flip axes to avoid sideways scrolling? The number of "prequisite-topics" will not fit to viewport width but the number of "own-topics" might. Also the scrolling could the be for the full viewport and not the matrix container.

Bonus: adding a course name info for each prequisite-topic would be easier this way.

**Comment by tulir** [comment]
Course matrix was deprecated, so this is no longer applicable
