### ISSUE TITLE
Number of columns based on menu open/closed

### ISSUE THREAD

**Issue by juhapekkamoilanen** [rage/concepts#75]
Space for concepts could be utilized better by setting number of columns based on whether courses menu is open or closed.

Here's some ideas of how this could be achieved:

https://github.com/rage/concepts/blob/602ccf770fa0cc79ee93b691768eaacb9f5d1ab2/frontend/src/components/course/CourseContainer.js#L18:

```js
const breakpointColumnsObj = {
  wide: {
    default: 6,
    2000: 5
    1690: 4,
    1380: 3,
    1070: 2,
    760: 1
  },
  narrow: {
    default: 3,
    1900: 2,
    1279: 1
  }
}
```

https://github.com/rage/concepts/blob/602ccf770fa0cc79ee93b691768eaacb9f5d1ab2/frontend/src/components/course/CourseContainer.js#L115
```js
<Masonry
  breakpointCols={conceptState.open ? breakpointColumnsObj.wide : conceptState.narrow}
  className="my-masonry-grid"
  columnClassName="my-masonry-grid_column"
>
```

**Comment by tulir** [comment]
This was fixed with the switch to pure CSS masonry
